name: Build

on:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: '0 0 * * 0'
# Run weekly, at 00:00 on sunday
#    tags:
#      - 'v*.*.*'

#pull_request:
#    branches:
#      - 'dev'
#      - 'testing'

# permissions are needed if pushing to ghcr.io ..
permissions:
  packages: write

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_DOCKER: index.docker.io
  GH_IMAGE_NAME: ghcr.io/${{ github.repository }}
  DH_IMAGE_NAME: index.docker.io/thefoundation
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  QU_REGISTRY_IMAGE: quay.io/thefoundation/library:${{ github.event.repository.name }}
 #QU_REGISTRY_IMAGE: quay.io/${{ github.repository }}/${{ github.event.repository.name }}
  BUILDCACHE: ghcr.io/${{ github.repository }}
  #BUILDCACHE: ghcr.io/${{ github.repository_owner }}/buildcache
  PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"
  #PLATFORMS: "linux/amd64"
  PLATFORMS_ALPINE: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
######  upstream:
######    runs-on: ubuntu-latest
######    environment: build
######    permissions:
######      packages: read
######      contents: read
######    if: github.repository_owner == 'TheFoundation'
######    steps:
######      - uses: actions/checkout@v3
######      - name: prep-downstream
######        run: |
######             mkdir downstream
######             cp -aurv _build_hocker.sh .github downstream &
######             tar cv . |md5sum |cut -d" " -f1 > downstream/.md5sum_of_tar
######             bash build/_generate_downstream_readme.sh thefoundation-builder hocker-builder-github > downstream/README.md
######             wait
#######      - uses: cpina/github-action-push-to-another-repository@main
######      - uses: TheFoundation/github-action-push-to-another-repository@main
######        env:
######          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
#######          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
######        with:
######          source-directory: 'downstream'
######          destination-github-username: 'thefoundation-builder'
######          destination-repository-name: 'hocker-builder-github'
######          user-email: actions@github.com
######          target-branch: main

  build-base:
    runs-on: ubuntu-latest
    container: quay.io/thefoundation/library:docker-with-buildx
    env:
      QUAY_PASS: ${{ secrets.QUAY_PASS }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      APT_HTTP_PROXY_URL: ${{ secrets.APT_HTTP_PROXY_URL }}

    environment: push-dockerhub
    permissions:
      packages: write
      contents: read
    if: github.repository_owner == 'thefoundation-builder'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: current images
        run: docker image ls
      - name: gnu date
        run: apk add coreutils
      - id: check_build_baseimage
        # Give an id to the step, so we can reference it later
        run: |
          echo "Detecting changed files"
          #echo "adding current path as safe dir"
          git config --global --add safe.directory  $(pwd)
          #echo "remoteURL is "$(git config --get remote.origin.url)
          #git clone $(git config --get remote.origin.url) /tmp/cleancheckout
          echo "Diff HEAD with the previous commit"
          diffed=$(git log -1 --oneline --name-only --pretty='' HEAD)
          changestatus=false
          echo "FILES CHANGED IN LAST COMMIT"
          echo "$diffed"
          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          echo "$diffed"  |grep -q -e "^Dockerfile.baseimage$" -e ^install-whim && changestatus=true  
          # Check if our baseimage is older than a week
          docker pull  $CI_REGISTRY_IMAGE:baseimage || true 
          imageagedays=$(( ( $(date +%s ) - $(date --date=$(docker image inspect $CI_REGISTRY_IMAGE:baseimage | jq .[]."Created" --raw-output) +%s) ) /(60*60*24) ))
          maxaimageage=6
          echo "imageage $imageagedays"
          [[ "$imageagedays" -gt "$maximageage" ]] && changestatus=true
          echo "answer to the did-files-change question is "$changestatus
          # Set the output named "do_the_build"
          ## DEPRECATED#echo#"::set-output name=do_the_build::$changestatus"
          echo "do_the_build=$changestatus" >> $GITHUB_OUTPUT
          #Write-Host "::set-output name=do_the_build::$HasDiff"
  
      # Run the steps only with "do_the_build" equals "True"
      - name: show steps
        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
        run: echo "pushing to $CI_REGISTRY_IMAGE BASEIMAGE cached by $BUILDCACHE"
      - name: show cmd
        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
        run: echo docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention -t $CI_REGISTRY_IMAGE:baseimage  -f Dockerfile.baseimage .
      - name: build BASE-images
        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
        run: docker buildx build --platform ${PLATFORMS}  --build-arg BUILDKIT_INLINE_CACHE=1 --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention_baseimage --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention -t $CI_REGISTRY_IMAGE:baseimage  -f Dockerfile.baseimage .
#      - name: "squash baseimage"
#        run: docker-squash-multiarch $CI_REGISTRY_IMAGE:baseimage
#
#      - name: build images
##        run: sudo /bin/bash -c "export REGISTRY_PASSWORD=$REGISTRY_PASSWORD;export REGISTRY_HOST=docker.io;export REGISTRY_PROJECT=thefoundation;export PROJECT_NAME=library;export REGISTRY_USER=${{ secrets.REGISTRY_USER }} ;bash _build_hocker.sh base-focal "
#        run: docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention -t $CI_REGISTRY_IMAGE:latest  -f Dockerfile .
#      -
#        name: Login to Quay Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: quay.io
#          username: ${{ secrets.QUAY_USER }}
#          password: ${{ secrets.QUAY_PASS }}
#      - name: build images to quay
#        run: docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention -t $QU_REGISTRY_IMAGE  -f Dockerfile .
      - name: show files
        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
#        run: bash -c "ls buildlogs/  -lh1 ; tail -n 20 buildlogs/*"
        run: docker image ls 
      - name: Archive production artifacts
        if: steps.check_build_baseimage.outputs.do_the_build== 'true' && failure()
        uses: actions/upload-artifact@v3
#        if: failure()
        with:
         name: buildlogs
         path: |
              buildlogs
      - name: non-builder-msg
        if: steps.check_build_baseimage.outputs.do_the_build!= 'true'
        run: echo "NOT BUILDING BASEIMAGE..NO CHANGES"

  build-final:
    runs-on: ubuntu-latest
    container: quay.io/thefoundation/library:docker-with-buildx
    needs: build-base
    env:
      QUAY_PASS: ${{ secrets.QUAY_PASS }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      APT_HTTP_PROXY_URL: ${{ secrets.APT_HTTP_PROXY_URL }}

    environment: push-dockerhub
    permissions:
      packages: write
      contents: read
    if: github.repository_owner == 'thefoundation-builder'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: current images
        run: docker image ls
      - name: show steps
        run: echo "pushing to $CI_REGISTRY_IMAGE cached by $BUILDCACHE"
      - name: show cmd
        run: echo docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention -t $CI_REGISTRY_IMAGE:latest  -f Dockerfile .
#      - name: build BASE-images
#        run: docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention_baseimage --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention_baseimage -t $CI_REGISTRY_IMAGE:baseimage  -f Dockerfile.baseimage .
#
      - name: build images
        run: docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention_baseimage -t $CI_REGISTRY_IMAGE:latest  -f Dockerfile .
      - name: Login to Quay Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}
      - name: build images to quay
        run: docker buildx build --platform ${PLATFORMS}  --push --pull --cache-to=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}__hugo_extended_webmention --cache-from=type=registry,ref=$BUILDCACHE:zzz_buildcache_${{ github.event.repository.name }}_hugo_extended_webmention_baseimage -t $QU_REGISTRY_IMAGE  -f Dockerfile .
  
      - name: show files
#        run: bash -c "ls buildlogs/  -lh1 ; tail -n 20 buildlogs/*"
        run: docker image ls 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
         name: buildlogs
         path: |
              buildlogs
